In [1]:
#Q1. Load the (SuperMarket Analysis.csv) dataset and display the first 5 rows.
import pandas as pd

df = pd.read_csv("SuperMarket Analysis.csv")
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [ ]:
df.sort_values(by=["Unit price, "Quantity"]

In [2]:
 #Q2. Display the dataset shape (rows and columns).
df.shape

(1000, 17)

In [3]:
#Q3. List all column names.
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [4]:
#Q4. Identify categorical and numerical columns.
categorical_cols = df.select_dtypes(include='object').columns
numerical_cols = df.select_dtypes(exclude='object').columns
print(categorical_cols)
print(numerical_cols)

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Date', 'Time', 'Payment'],
      dtype='object')
Index(['Unit price', 'Quantity', 'Tax 5%', 'Sales', 'cogs',
       'gross margin percentage', 'gross income', 'Rating'],
      dtype='object')

In [6]:
# Q5. Check missing values per column
df.isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [7]:
#Q6. Display the data types of each column.
df.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [8]:
#Q7. Show summary statistics for numerical columns (use pandas method).
df.describe()

,Unit price,Quantity,Tax 5%,Sales,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905e+00,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,6.131498e-14,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905e+00,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905e+00,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905e+00,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905e+00,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905e+00,49.650000,10.00000

In [10]:
#Q8. Filter rows where Sales > 500
df[df["Sales"] > 500]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
991,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,6:10:00 PM,Ewallet,766.00,4.761905,38.3000,6.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [11]:
#Q9. Filter sales in City = “Yangon” and Sales > 200.
df[(df["City"] == "Yangon") & (df["Sales"] > 200)].sort_values(by="Sales", ascending=False)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
167,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2/8/2019,4:20:00 PM,Credit card,989.80,4.761905,49.4900,8.7
429,325-77-6186,Alex,Yangon,Member,Female,Home and lifestyle,90.65,10,45.3250,951.8250,3/8/2019,10:53:00 AM,Ewallet,906.50,4.761905,45.3250,7.3
959,384-59-6655,Alex,Yangon,Member,Female,Food and beverages,98.66,9,44.3970,932.3370,2/19/2019,3:07:00 PM,Cash,887.94,4.761905,44.3970,8.4
105,704-48-3927,Alex,Yangon,Member,Female,Electronic accessories,88.67,10,44.3350,931.0350,1/12/2019,2:50:00 PM,Ewallet,886.70,4.761905,44.3350,7.3
529,827-77-7633,Alex,Yangon,Normal,Male,Sports and travel,98.09,9,44.1405,926.9505,2/17/2019,7:41:00 PM,Cash,882.81,4.761905,44.1405,9.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,254-31-0042,Alex,Yangon,Member,Male,Electronic accessories,21.50,9,9.6750,203.1750,3/6/2019,12:46:00 PM,Credit card,193.50,4.761905,9.6750,7.8
505,726-29-6793,Alex,Yangon,Member,Male,Electronic accessories,24.18,8,9.6720,203.1120,1/28/2019,8:54:00 PM,Ewallet,193.44,4.761905,9.6720,9.8
33,595-11-5460,Alex,Yangon,Member,Female,Health and beauty,96.58,2,9.6580,202.8180,3/15/2019,10:12:00 AM,Credit card,193.16,4.761905,9.6580,5.1
836,288-62-1085,Alex,Yangon,Member,Male,Fashion accessories,38.54,5,9.6350,202.3350,1/9/2019,1:34:00 PM,Ewallet,192.70,4.761905,9.6350,5.6
284,565-17-3836,Alex,Yangon,Member,Female,Health and beauty,47.67,4,9.5340,200.2140,3/12/2019,2:21:00 PM,Cash,190.68,4.761905,9.5340,9.1

In [12]:
#Q10. Sort all orders by Sales in descending order.
df.sort_values(by="Sales", ascending=False)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
350,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.6500,1042.6500,2/15/2019,2:53:00 PM,Credit card,993.00,4.761905,49.6500,6.6
167,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2/8/2019,4:20:00 PM,Credit card,989.80,4.761905,49.4900,8.7
557,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,1/30/2019,8:23:00 PM,Ewallet,985.20,4.761905,49.2600,4.5
699,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,1/12/2019,4:18:00 PM,Ewallet,975.00,4.761905,48.7500,8.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,236-86-3015,Giza,Naypyitaw,Member,Male,Home and lifestyle,13.98,1,0.6990,14.6790,2/4/2019,1:38:00 PM,Ewallet,13.98,4.761905,0.6990,9.8
443,192-98-7397,Giza,Naypyitaw,Normal,Male,Fashion accessories,12.78,1,0.6390,13.4190,1/8/2019,2:11:00 PM,Ewallet,12.78,4.761905,0.6390,9.5
223,279-62-1445,Giza,Naypyitaw,Member,Female,Fashion accessories,12.54,1,0.6270,13.1670,2/21/2019,12:38:00 PM,Cash,12.54,4.761905,0.6270,8.2
629,308-39-1707,Alex,Yangon,Normal,Female,Fashion accessories,12.09,1,0.6045,12.6945,1/26/2019,6:19:00 PM,Credit card,12.09,4.761905,0.6045,8.2
822,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,2:15:00 PM,Cash,10.17,4.761905,0.5085,5.9

In [13]:
# Q11. Sort by Date (ascending) and then Time (ascending).
df.sort_values(by=["Date", "Time"], ascending=[True, True])

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
17,765-26-6951,Alex,Yangon,Member,Female,Sports and travel,72.61,6,21.783,457.443,1/1/2019,10:39:00 AM,Credit card,435.66,4.761905,21.783,6.9
970,746-04-1077,Cairo,Mandalay,Member,Female,Food and beverages,84.63,10,42.315,888.615,1/1/2019,11:36:00 AM,Credit card,846.30,4.761905,42.315,9.0
839,271-77-8740,Giza,Naypyitaw,Member,Female,Sports and travel,29.22,6,8.766,184.086,1/1/2019,11:40:00 AM,Ewallet,175.32,4.761905,8.766,5.0
523,133-14-7229,Giza,Naypyitaw,Normal,Male,Health and beauty,62.87,2,6.287,132.027,1/1/2019,11:43:00 AM,Cash,125.74,4.761905,6.287,5.0
567,651-88-7328,Alex,Yangon,Normal,Female,Fashion accessories,65.74,9,29.583,621.243,1/1/2019,1:55:00 PM,Cash,591.66,4.761905,29.583,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,219-22-9386,Cairo,Mandalay,Member,Female,Sports and travel,99.96,9,44.982,944.622,3/9/2019,5:26:00 PM,Credit card,899.64,4.761905,44.982,4.2
45,132-32-9879,Cairo,Mandalay,Member,Female,Electronic accessories,93.96,4,18.792,394.632,3/9/2019,6:00:00 PM,Cash,375.84,4.761905,18.792,9.5
73,841-35-6630,Giza,Naypyitaw,Member,Female,Electronic accessories,75.91,6,22.773,478.233,3/9/2019,6:21:00 PM,Cash,455.46,4.761905,22.773,8.7
234,157-13-5295,Alex,Yangon,Member,Male,Health and beauty,51.94,10,25.970,545.370,3/9/2019,6:24:00 PM,Ewallet,519.40,4.761905,25.970,6.5
326,815-11-1168,Alex,Yangon,Member,Male,Food and beverages,99.78,5,24.945,523.845,3/9/2019,7:09:00 PM,Cash,498.90,4.761905,24.945,5.4

In [14]:
#Q12. Sort by Unit price and Quantity.
df.sort_values(by=["Unit price", "Quantity"], ascending=[True, True])

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
944,333-23-2632,Alex,Yangon,Member,Male,Health and beauty,10.08,7,3.5280,74.0880,3/28/2019,8:14:00 PM,Cash,70.56,4.761905,3.5280,4.2
572,239-48-4278,Alex,Yangon,Member,Male,Food and beverages,10.13,7,3.5455,74.4555,3/10/2019,7:35:00 PM,Ewallet,70.91,4.761905,3.5455,8.3
784,516-77-6464,Giza,Naypyitaw,Member,Female,Health and beauty,10.16,5,2.5400,53.3400,2/24/2019,1:08:00 PM,Ewallet,50.80,4.761905,2.5400,4.1
822,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,2:15:00 PM,Cash,10.17,4.761905,0.5085,5.9
881,115-38-7388,Giza,Naypyitaw,Member,Female,Fashion accessories,10.18,8,4.0720,85.5120,3/30/2019,12:51:00 PM,Credit card,81.44,4.761905,4.0720,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,667-92-0055,Alex,Yangon,Member,Male,Health and beauty,99.83,6,29.9490,628.9290,3/4/2019,3:02:00 PM,Ewallet,598.98,4.761905,29.9490,8.5
494,437-53-3084,Cairo,Mandalay,Normal,Male,Fashion accessories,99.89,2,9.9890,209.7690,2/26/2019,11:48:00 AM,Ewallet,199.78,4.761905,9.9890,7.1
930,641-62-7288,Cairo,Mandalay,Normal,Male,Home and lifestyle,99.92,6,29.9760,629.4960,3/24/2019,1:33:00 PM,Ewallet,599.52,4.761905,29.9760,7.1
983,148-41-7930,Giza,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.9860,734.7060,1/23/2019,10:33:00 AM,Cash,699.72,4.761905,34.9860,6.1
122,219-22-9386,Cairo,Mandalay,Member,Female,Sports and travel,99.96,9,44.9820,944.6220,3/9/2019,5:26:00 PM,Credit card,899.64,4.761905,44.9820,4.2

In [15]:
#Q13. Calculate the total sales in “Sales” per Branch.
df.groupby("Branch")["Sales"].sum()

Branch
Alex     106200.3705
Cairo    106197.6720
Giza     110568.7065
Name: Sales, dtype: float64

In [16]:
#Q14. Calculate average Sales per City.
df.groupby("City")["Sales"].mean()

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Sales, dtype: float64

In [17]:
#Q15. Find the quantities sold per product line.
df.groupby("Product line")["Quantity"].sum()

Product line
Electronic accessories    971
Fashion accessories       902
Food and beverages        952
Health and beauty         854
Home and lifestyle        911
Sports and travel         920
Name: Quantity, dtype: int64

In [18]:
#Q16. Calculate average gross income per Gender.
df.groupby("Gender")["gross income"].mean()

Gender
Female    16.234829
Male      14.240749
Name: gross income, dtype: float64

In [19]:
#Q17. Count number of sales per Payment method.
df.groupby("Payment").size()

Payment
Cash           344
Credit card    311
Ewallet        345
dtype: int64

In [20]:
#Q18. Find maximum Sales per Branch.

df.groupby("Branch")["Sales"].max()

Branch
Alex     1039.29
Cairo    1022.49
Giza     1042.65
Name: Sales, dtype: float64

In [21]:
#Q19. Find minimum Unit price per Product line.
df.groupby("Product line")["Unit price"].min()

Product line
Electronic accessories    10.56
Fashion accessories       10.18
Food and beverages        10.13
Health and beauty         10.08
Home and lifestyle        10.53
Sports and travel         10.17
Name: Unit price, dtype: float64

In [22]:
 #Q20. Find the sum of gross income per Product line and Branch.
df.groupby(["Product line", "Branch"])["gross income"].sum()

Product line            Branch
Electronic accessories  Alex       872.2435
                        Cairo      811.9735
                        Giza       903.2845
Fashion accessories     Alex       777.7385
                        Cairo      781.5865
                        Giza      1026.6700
Food and beverages      Alex       817.2905
                        Cairo      724.5185
                        Giza      1131.7550
Health and beauty       Alex       599.8930
                        Cairo      951.4600
                        Giza       791.2060
Home and lifestyle      Alex      1067.4855
                        Cairo      835.6745
                        Giza       661.6930
Sports and travel       Alex       922.5095
                        Cairo      951.8190
                        Giza       750.5680
Name: gross income, dtype: float64

In [23]:
#21. What is the total quantities sold in Product line: “Electronic accessories”?
df.loc[df["Product line"] == "Electronic accessories", "Quantity"].sum()

971

In [24]:
#22. What is the average Sales for female customers?
df[df["Gender"] == "Female"]["Sales"].mean()

340.9314141856392

In [25]:
#23. What is the most expensive Unit price among Customer type members only?
df[df["Customer type"] == "Member"]["Unit price"].max()

99.96

In [ ]:
df[df["Customer type"]=="Member"]["Unit price"].max()
(df["Rating"]>=9).sum()

df[(df["Payment"]=="Credit card") & (df["Branch

In [26]:
#24. How many orders with Rating >= 9 ?
(df["Rating"] >= 9).sum()

166

In [27]:
#25. What is the total Sales for Payment “Credit card” in Branch C?
df[(df["Payment"] == "Credit card") & (df["Branch"] == "C")]["Sales"].sum()

0.0